#!/bin/sh
echo "********************************"
echo " Exec rcS "
echo "********************************"

runlevel=S
export runlevel

# Host name
/bin/hostname Linux

# Mount /proc if not
[ -d "/proc/1" ] || mount /proc

mkdir -p /dev/pts /dev/shm

echo "********mount all********"
/bin/mount -av

# /dev was mounted before but with a rather large size so let's adjust that.
mount -t tmpfs tmpfs /dev -o remount,size=512k

if false; then
  # Read the busybox docs: mdev.txt
  echo "********Starting mdev********"
  echo "This may take some time ..."
  /bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
  mdev -s
fi

# Start local services
/etc/init.d/rc.local

echo "********************************"
echo "********************************"

echo "Login as 'root'."
